### ISSUE TITLE
Error: Request failed with status code 500 on search

### ISSUE THREAD

**Issue by IsidroMar95** [jamesdordoy/laravel-vue-datatable#46]
the search input works but sometimes when i write a long sentence and keep the delete buton pressed to delete the words in the input and the input is empty returns an error 
![20200117_130843](https://user-images.githubusercontent.com/23019968/72639184-a782d380-392a-11ea-8217-fe41ac8dbcd2.gif)

**Comment by jamesdordoy** [comment]
Would you mind posting the 500 error value?

I cant replicate this locally.

**Comment by IsidroMar95** [comment]
idk if this is a bad config on my own , i'm just typing a few words
<img width="960" alt="Screenshot_1" src="https://user-images.githubusercontent.com/23019968/72640054-ae124a80-392c-11ea-9cfb-d85dfbe962b0.png">

the error message is not explicit so i can not know what is going on
<img width="960" alt="Screenshot_2" src="https://user-images.githubusercontent.com/23019968/72640104-cda97300-392c-11ea-8465-55f519eaaf62.png">

<img width="960" alt="Screenshot_3" src="https://user-images.githubusercontent.com/23019968/72640114-d5691780-392c-11ea-80b5-bf2bdf503d81.png">

**Comment by jamesdordoy** [comment]
If you can would you mind checking your Laravel error logs?

You can find them at `/storage/logs/laravel-{todaysDate}.log`

I'm trying to replicate the error on the documentation tables and i'm not able to so i'm not sure if this is specific to the package or not.

**Comment by IsidroMar95** [comment]
yes, this is the error on the log
```
[2020-01-17 19:59:34] production.ERROR: No application encryption key has been specified. {"exception":"[object] (RuntimeException(code: 0): No application encryption key has been specified. at C:\\laragon\\www\\laravel-vue-datatable\\vendor\\laravel\\framework\\src\\Illuminate\\Encryption\\EncryptionServiceProvider.php:44)
[stacktrace]
#0 C:\\laragon\\www\\laravel-vue-datatable\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\helpers.php(422): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}(NULL)
#1 C:\\laragon\\www\\laravel-vue-datatable\\vendor\\laravel\\framework\\src\\Illuminate\\Encryption\\EncryptionServiceProvider.php(48): tap(NULL, Object(Closure))
#2 C:\\laragon\\www\\laravel-vue-datatable\\vendor\\laravel\\framework\\src\\Illuminate\\Encryption\\EncryptionServiceProvider.php(24): Illuminate\\Encryption\\EncryptionServiceProvider->key(Array)
#3 C:\\laragon\\www\\laravel-vue-datatable\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(799): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
#4 C:\\laragon\\www\\laravel-vue-datatable\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(681): Illuminate\\Container\\Container->build(Object(Closure))
#5 C:\\laragon\\www\\laravel-vue-datatable\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(629): Illuminate\\Container\\Container->resolve('encrypter', Array)
#6 C:\\laragon\\www\\laravel-vue-datatable\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(776): Illuminate\\Container\\Container->make('encrypter', Array)
#7 C:\\laragon\\www\\laravel-vue-datatable\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(945): Illuminate\\Foundation\\Application->make('encrypter')
#8 C:\\laragon\\www\\laravel-vue-datatable\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(873): Illuminate\\Container\\Container->resolveClass(Object(ReflectionParameter))
#9 C:\\laragon\\www\\laravel-vue-datatable\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(834): Illuminate\\Container\\Container->resolveDependencies(Array)
#10 C:\\laragon\\www\\laravel-vue-datatable\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(681): Illuminate\\Container\\Container->build('App\\\\Http\\\\Middle...')
#11 C:\\laragon\\www\\laravel-vue-datatable\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(629): Illuminate\\Container\\Container->resolve('App\\\\Http\\\\Middle...', Array)
#12 C:\\laragon\\www\\laravel-vue-datatable\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(776): Illuminate\\Container\\Container->make('App\\\\Http\\\\Middle...', Array)
#13 C:\\laragon\\www\\laravel-vue-datatable\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(160): Illuminate\\Foundation\\Application->make('App\\\\Http\\\\Middle...')
#14 C:\\laragon\\www\\laravel-vue-datatable\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#15 C:\\laragon\\www\\laravel-vue-datatable\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(683): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#16 C:\\laragon\\www\\laravel-vue-datatable\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#17 C:\\laragon\\www\\laravel-vue-datatable\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(624): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#18 C:\\laragon\\www\\laravel-vue-datatable\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#19 C:\\laragon\\www\\laravel-vue-datatable\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(170): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#20 C:\\laragon\\www\\laravel-vue-datatable\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#21 C:\\laragon\\www\\laravel-vue-datatable\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 C:\\laragon\\www\\laravel-vue-datatable\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 C:\\laragon\\www\\laravel-vue-datatable\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 C:\\laragon\\www\\laravel-vue-datatable\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 C:\\laragon\\www\\laravel-vue-datatable\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 C:\\laragon\\www\\laravel-vue-datatable\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 C:\\laragon\\www\\laravel-vue-datatable\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 C:\\laragon\\www\\laravel-vue-datatable\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 C:\\laragon\\www\\laravel-vue-datatable\\vendor\\fideloper\\proxy\\src\\TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 C:\\laragon\\www\\laravel-vue-datatable\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 C:\\laragon\\www\\laravel-vue-datatable\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 C:\\laragon\\www\\laravel-vue-datatable\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#33 C:\\laragon\\www\\laravel-vue-datatable\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#34 C:\\laragon\\www\\laravel-vue-datatable\\public\\index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#35 {main}
"} 
[2020-01-17 19:59:34] production.ERROR: No application encryption key has been specified. {"exception":"[object] (RuntimeException(code: 0): No application encryption key has been specified. at C:\\laragon\\www\\laravel-vue-datatable\\vendor\\laravel\\framework\\src\\Illuminate\\Encryption\\EncryptionServiceProvider.php:44)
[stacktrace]
#0 C:\\laragon\\www\\laravel-vue-datatable\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\helpers.php(422): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}(NULL)
#1 C:\\laragon\\www\\laravel-vue-datatable\\vendor\\laravel\\framework\\src\\Illuminate\\Encryption\\EncryptionServiceProvider.php(48): tap(NULL, Object(Closure))
#2 C:\\laragon\\www\\laravel-vue-datatable\\vendor\\laravel\\framework\\src\\Illuminate\\Encryption\\EncryptionServiceProvider.php(24): Illuminate\\Encryption\\EncryptionServiceProvider->key(Array)
#3 C:\\laragon\\www\\laravel-vue-datatable\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(799): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
#4 C:\\laragon\\www\\laravel-vue-datatable\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(681): Illuminate\\Container\\Container->build(Object(Closure))
#5 C:\\laragon\\www\\laravel-vue-datatable\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(629): Illuminate\\Container\\Container->resolve('encrypter', Array)
#6 C:\\laragon\\www\\laravel-vue-datatable\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(776): Illuminate\\Container\\Container->make('encrypter', Array)
#7 C:\\laragon\\www\\laravel-vue-datatable\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(945): Illuminate\\Foundation\\Application->make('encrypter')
#8 C:\\laragon\\www\\laravel-vue-datatable\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(873): Illuminate\\Container\\Container->resolveClass(Object(ReflectionParameter))
#9 C:\\laragon\\www\\laravel-vue-datatable\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(834): Illuminate\\Container\\Container->resolveDependencies(Array)
#10 C:\\laragon\\www\\laravel-vue-datatable\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(681): Illuminate\\Container\\Container->build('App\\\\Http\\\\Middle...')
#11 C:\\laragon\\www\\laravel-vue-datatable\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(629): Illuminate\\Container\\Container->resolve('App\\\\Http\\\\Middle...', Array)
#12 C:\\laragon\\www\\laravel-vue-datatable\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(776): Illuminate\\Container\\Container->make('App\\\\Http\\\\Middle...', Array)
#13 C:\\laragon\\www\\laravel-vue-datatable\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(209): Illuminate\\Foundation\\Application->make('App\\\\Http\\\\Middle...')
#14 C:\\laragon\\www\\laravel-vue-datatable\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(183): Illuminate\\Foundation\\Http\\Kernel->terminateMiddleware(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\JsonResponse))
#15 C:\\laragon\\www\\laravel-vue-datatable\\public\\index.php(60): Illuminate\\Foundation\\Http\\Kernel->terminate(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\JsonResponse))
#16 {main}
"} 

```

**Comment by jamesdordoy** [comment]
It looks like you have not set your app key in your .env file.

This can be done by running the following command:

`php artisan key:generate`

If that isn't the case, That error is specific the Laravel framework as none of the package code is throwing an exception. I'm not sure what else would cause it.

**Comment by IsidroMar95** [comment]
I thought the same thing, but in my .env the secret key is set :(. 
<img width="410" alt="Screenshot_1" src="https://user-images.githubusercontent.com/23019968/72642851-eddc3080-3932-11ea-9848-24d3b0038da0.png">

**Comment by jamesdordoy** [comment]
Ahh fair play,

I guess the only other thing i could do is implement debouncing on the search box so that if the issue is being caused by the requests firing off too fast, i can slow them down until the user finishes typing.

I guess it would be a nice addition to the table anyway but would require additional dependencies like lodash.

**Comment by IsidroMar95** [comment]
It seems it working now, the only thing I did was run these commands :
```
php artisan key:generate
php artisan config:cache
```
one more time i apologize for submiting so many issues but i'm kinda newbie with Vue

**Comment by jamesdordoy** [comment]
Ahh yeah your .env file gets cached.

No worries, no need to apologize. Hope you like Vue :).
